# These are supported funding model platforms

github: # Sayyidalijufri
patreon: # Ali
open_collective: # Sayyid Ali Aljufri
ko_fi: # Programingwithali
tidelift: # Saweria
community_bridge: # I don't have a community
liberapay: # Rhttps://saweria.co/Programingwithali
issuehunt: # https://saweria.co/Programingwithali
otechie: # https://saweria.co/Programingwithali
custom: # https://saweria.co/Programingwithali
